server:   
   port: 9527 
spring:   
   application:    
      name: microservicecloud-zuul-gateway 
eureka:   
   client:
      register-with-eureka: true #false表示不向注册中心注册自己。    
      fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务    
      service-url:       
         defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka    
   instance:    
      instance-id: gateway-9527.com    
      prefer-ip-address: true
#before http://myzuul.com:9527/microservicecloud-dept/dept/get/2  
zuul:  
   #ignored-services: microservicecloud-dept
   ignored-services: '*'
   prefix: /atguigu   
   routes:
      mydept.serviceId: microservicecloud-dept    
      mydept.path: /mydept/** 
#after http://myzuul.com:9527/mydept/dept/get/1 
info:  
   app.name:  atguigu-microcloud  
   company.name: www.atguigu.com  
   build.artifactId: $project.artifactId$  
   build.version: $project.version$